# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='not_confirm', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='students',
            field=models.ManyToManyField(through='activity.Confirm_state', to='student.Student'),
        ),
        migrations.AddField(
            model_name='confirm_state',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
        migrations.AddField(
            model_name='confirm_state',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
