# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 07:57
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20171102_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(max_length=200),
        ),
    ]
