# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
                ('time_worth', models.IntegerField(default=1)),
                ('place', models.CharField(max_length=200)),
                ('number_of_volunteers', models.IntegerField(default=1)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Organizer')),
                ('students', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
