# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
                ('time_worth', models.IntegerField(default=1)),
                ('place', models.CharField(max_length=200)),
                ('number_of_volunteers', models.IntegerField(default=1)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Confirm_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='not_confirm', max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='students',
            field=models.ManyToManyField(through='activity.Confirm_state', to='student.Student'),
        ),
    ]
