# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('activity', '0002_auto_20171031_1917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='confirm_state',
            unique_together=set([('student', 'activity')]),
        ),
    ]
