# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 08:36
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20171102_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='major',
            field=fernet_fields.fields.EncryptedCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=fernet_fields.fields.EncryptedCharField(max_length=200),
        ),
    ]
