# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 08:41
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20171110_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time_worth1',
            field=fernet_fields.fields.EncryptedIntegerField(default=1),
        ),
    ]
