# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major_dup',
            field=models.CharField(choices=[('Math', 'Math'), ('Computer Science', 'Computer Science'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Programming', 'Programming')], default='Math', max_length=20),
        ),
    ]
