# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_major_dup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
    ]
