# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='major_dup',
            new_name='major',
        ),
    ]
